;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; el-get packages
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(el-get-bundle ddskk)
;(el-get-bundle auto-complete)
;(el-get-bundle color-moccur)
(el-get-bundle elscreen)
(el-get-bundle migemo)
(el-get-bundle emacs-async)
(el-get-bundle helm)
(el-get-bundle helm-descbinds)
;(el-get-bundle helm-migemo)
(el-get-bundle helm-swoop)
(el-get-bundle helm-ag)
(el-get-bundle org)
(el-get-bundle popup-kill-ring)
(el-get-bundle color-theme-zenburn)
;(el-get-bundle howm)
;(el-get-bundle moccur-edit)
;(el-get-bundle visual-basic-mode)
(el-get-bundle point-undo)
(el-get-bundle markdown-mode)
(el-get-bundle company-mode)
(el-get-bundle company-quickhelp)
(el-get-bundle goto-chg)
(el-get-bundle google-translate)
(el-get-bundle bm)
(el-get-bundle go-mode)
(el-get-bundle go-eldoc)
(el-get-bundle! company-go :url "https://raw.githubusercontent.com/nsf/gocode/master/emacs-company/company-go.el")
(el-get-bundle flycheck)
(el-get-bundle flycheck-rust)
(el-get-bundle rust-mode)
(el-get-bundle emacs-racer)
(el-get-bundle tarao/el-get-lock)
;(el-get-bundle fsharp-mode)
(el-get-lock)
